

local L = AceLibrary("AceLocale-2.2"):new("LazySpell")

L:RegisterTranslations("ruRU", function() return {

	["Options"] = "Настройки",
	["Open options"] = "Открыть настройки",
	["Spell options"] = "Настройки заклинаний",
	["Options for min\max rank spell to subtitude and overheal coef."] = "Настройки минимальных\максимальных рангов заклинаний для подмены и значение коэфицента избыточного исцеления",
	["Overheal ratio"] = "Коэфицент избыточного исцеления",
	["Ratio of overheal of spells from 0.1 to 2"] = "Коэфицент избыточного исцеления для заклинаний от 0.1 (недо-исцеление) до 2 (избыточное исцеление)",
	["Healing Wave Max Rank"] = "Волна исцеления",
	["Defines the max rank of Healing Wave spell used by lazyspell."] = "Устанавливает максимальный ранг заклинания Волна исцеления, используемый lazyspell",
	["Min Rank for HW"] = "Миниммальный Ранг для ВИ",
	["Use minimum Rank for Healing Wave"] = "Минимальный ранг Волны исцеления",
	["Lesser Healing Wave Max Rank"] = "Малая волна исцеления",
	["Defines the max rank of Lesser Healing Wave spell used by lazyspell."] = "Устанавливает максимальный ранг заклинания Малая волна исцеления, используемый lazyspell",
	["Min Rank for LHW"] = "Миниммальный Ранг для МВИ",
	["Use minimum Rank for Lesser Healing Wave"] = "Минимальный ранг Малой волны исцеления",
	["Chain Heal Max Rank"] = "Цепное исцеление",
	["Defines the max rank of Chain Heal spell used by lazyspell."] = "Устанавливает максимальный ранг заклинания Цепное исцеление, используемый lazyspell",
	["Heal Max Rank"] = "Исцеление",
	["Defines the max rank of Heal spell used by lazyspell."] = "Устанавливает максимальный ранг заклинания Исцеление, используемый lazyspell",
	["Flash Heal Max Rank"] = "Быстрое исцеление",
	["Defines the max rank of Flash Heal spell used by lazyspell."] = "Устанавливает максимальный ранг заклинания Быстрое исцеление, используемый lazyspell",
	["Greater Heal Max Rank"] = "Великое исцеление",
	["Defines the max rank of Greater Heal spell used by lazyspell."] = "Устанавливает максимальный ранг заклинания Великое исцеление, используемый lazyspell",
	["Hide minimap icon"] = "Спрятать иконку у миникарты",
	["Lazy Spell Options"] = "Настройки Lazy Spell",
	["Healing Touch Max Rank"] = "Целительное прикосновение",
	["Defines the max rank of Healing Touch spell used by lazyspell."] = "Устанавливает максимальный ранг заклинания Целительное прикосновение, используемый lazyspell",
	["Healing Touch Min Rank"] = "Минимальный ранг Целительного прикосновения",
	["Defines the min rank of Healing Touch spell used by lazyspell."] = "Устанавливает минимальный ранг заклинания Целительное прикосновение, используемый lazyspell",
	["Regrowth Max Rank"] = "Восстановление",
	["Defines the max rank of Regrowth spell used by lazyspell."] = "Устанавливает максимальный ранг заклинания Восстановление, используемый lazyspell",
	["Regrowth Min Rank"] = "Минимальный ранг Восстановления",
	["Defines the min rank of Regrowth spell used by lazyspell."] = "Устанавливает минимальный ранг заклинания Восстановление, используемый lazyspell",
	["Fubar plugin"] = "Fubar плугин",
	["Fubar plugin options."] = "Настройка Fubar плугина",
} end)
